#export MESA_LOADER_DRIVER_OVERRIDE=crocus
export MESA_LOADER_DRIVER_OVERRIDE=i915

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export INPUT_METHOD="fcitx"
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
fcitx &
